# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StateAndReward.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StateAndReward.proto',
  package='service',
  syntax='proto3',
  serialized_options=b'Z\014./;rpcClient',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14StateAndReward.proto\x12\x07service\",\n\x0bStateReward\x12\r\n\x05state\x18\x01 \x03(\x02\x12\x0e\n\x06reward\x18\x02 \x01(\x02\"\x18\n\x06\x41\x63tion\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x02\x32L\n\x0b\x61\x63\x65rService\x12=\n\x14GetExplorationAction\x12\x14.service.StateReward\x1a\x0f.service.ActionB\x0eZ\x0c./;rpcClientb\x06proto3'
)




_STATEREWARD = _descriptor.Descriptor(
  name='StateReward',
  full_name='service.StateReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='service.StateReward.state', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reward', full_name='service.StateReward.reward', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=77,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='service.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='service.Action.action', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['StateReward'] = _STATEREWARD
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StateReward = _reflection.GeneratedProtocolMessageType('StateReward', (_message.Message,), {
  'DESCRIPTOR' : _STATEREWARD,
  '__module__' : 'StateAndReward_pb2'
  # @@protoc_insertion_point(class_scope:service.StateReward)
  })
_sym_db.RegisterMessage(StateReward)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'StateAndReward_pb2'
  # @@protoc_insertion_point(class_scope:service.Action)
  })
_sym_db.RegisterMessage(Action)


DESCRIPTOR._options = None

_ACERSERVICE = _descriptor.ServiceDescriptor(
  name='acerService',
  full_name='service.acerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=105,
  serialized_end=181,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetExplorationAction',
    full_name='service.acerService.GetExplorationAction',
    index=0,
    containing_service=None,
    input_type=_STATEREWARD,
    output_type=_ACTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACERSERVICE)

DESCRIPTOR.services_by_name['acerService'] = _ACERSERVICE

# @@protoc_insertion_point(module_scope)
